#   Differ between List and Numpy

**. Time Taken through List**

In [1]:
import time
Start = time.time()

list1 = [i for i in range(10000000)]
list2 = [i for i in range(10000000, 20000000)]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i] + list2[i])
print(f"Tike taken Through list = ", time.time()-Start)

Tike taken Through list =  8.53174352645874


***. Time Taken through Numpy***


In [2]:
import numpy as np 
import time

Start = time.time()

list1 = np.arange(10000000)
list2 = np.arange(10000000,20000000)

list3 = list1+list2

print(f"Tike taken Through Numpy = ", time.time()-Start)

Tike taken Through Numpy =  1.0004949569702148


# Array insilization through Numpy

In [3]:
import numpy as np

first_array = np.array([1,2,3,4])

first_array

array([1, 2, 3, 4])

***Sum of All Array and its type***

In [4]:
import numpy as np

arr = np.array([5, 1, 3, 4, 9])
result = np.sum(arr)

print("List = ",arr)
print("Sum  = ",result)
print("Type = ",type(result))

List =  [5 1 3 4 9]
Sum  =  22
Type =  <class 'numpy.int64'>


In [5]:
import numpy as np

arr = np.array([5, 6, 2, 7, 9])

for i in range(len(arr)):
    print(i+1," = ", arr[i])

# for value in arr:
#     print(value)

1  =  5
2  =  6
3  =  2
4  =  7
5  =  9


In [6]:
import numpy as np

arr = np.array([4, 2, 3, 9, 10])

print(arr[1:4])
print(arr[2:])
print(arr[-2:])

[2 3 9]
[ 3  9 10]
[ 9 10]


In [7]:
import numpy as np

arr = np.array([5, 3, 1, 2, 9, 7, 56])

print(arr[::3])

[ 5  2 56]


In [8]:
import numpy as np

arr = np.array([4, 3, 1, 9, 6, 2])

print(arr[::-1])

[2 6 9 1 3 4]


In [9]:
import numpy as np

arr = np.array([5, 3, 7, 9, 6, 2])

arr[2:4] = 25
print(arr)

[ 5  3 25 25  6  2]


In [10]:
import numpy as np

range = np.arange(1,11)

print(range)

[ 1  2  3  4  5  6  7  8  9 10]


# MultiDimensional Array

In [11]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'],['G', 'H', 'I']],
                  [['j', 'k', 'k'], ['m', 'n', 'o'],['p', 'q', 'r']],
                  [['s', 't', 'U'], ['V', 'W', 'X'],['Y', 'Z', ' ']]])

print(array)

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['j' 'k' 'k']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['s' 't' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' ' ']]]


In [12]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'],['G', 'H', 'I']],
                  [['j', 'k', 'k'], ['m', 'n', 'o'],['p', 'q', 'r']],
                  [['s', 't', 'U'], ['V', 'W', 'X'],['Y', 'Z', ' ']]])


print(array.ndim,"Dimensional")
print("Shape  = ", array.shape)


3 Dimensional
Shape  =  (3, 3, 3)


In [13]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'],['G', 'H', 'I']],
                  [['j', 'k', 'k'], ['m', 'n', 'o'],['p', 'q', 'r']],
                  [['S', 't', 'U'], ['V', 'W', 'X'],['Y', 'Z', ' ']]])


print(array[2, 0, 2])

U


In [14]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'],['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'],['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'],['Y', 'Z', ' ']]])


word = array[0,0,0] + array[2,2,0] + array[2,0,2] + array[2,0,0] + array[0,2,1]
print(word)

AYUSH


In [ ]:
# Practice Question Of Numpy

***1. Create a NumPy array of numbers from 1 to 10.***

In [15]:
NumpyArray = np.arange(1,11)

print(NumpyArray)

[ 1  2  3  4  5  6  7  8  9 10]


***2. Create an array of all zeros of size (3×3).***

In [16]:
zero = np.zeros((3,3), dtype = int)

print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


***3. Create an array of all ones of size (2×4).***

In [17]:
one = np.ones((2,4), dtype = int)

print(one)

[[1 1 1 1]
 [1 1 1 1]]


***4. Find the shape and dimension of this array:***

In [18]:
a = np.array([[1,2,3],[4,5,6]])

print(a.shape)
print(a.ndim) #No Of Dimensions

(2, 3)
2


***5. Print only the last element of:***

In [19]:
arr = np.array([10, 20, 30, 40])

print(arr[3])

40


***6. Create a 2D array and print:***

***. First row***

***. Second column***

In [20]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print("First row: ",arr[0])
print("Second Colomn: ", arr[:, 1])

First row:  [1 2 3]
Second Colomn:  [2 5]


***7. Create this array using NumPy:***

**[[1,2,3],**
**[4,5,6],**
**[7,8,9]]**

**Then print:**

**Element 5**

**Entire second row**

In [21]:
ayu = np.array([[
                    [1,2,3], 
                    [4,5,6], 
                    [7,8,9]
               ]])

print(ayu[0,1,1])
print(ayu[0,1,:])

5
[4 5 6]


**8. Reshape this array into (2×3):**

**. arr = np.array([1,2,3,4,5,6])**

In [22]:
re = np.array([1,2,3,4,5,6])

new_array = re.reshape(2,3)

print(new_array)


[[1 2 3]
 [4 5 6]]


**9. Find max, min, and sum of:**

In [23]:
arr = np.array([3, 7, 2, 9, 1])

print("Max = ",arr.max())
print("Min = ",arr.min())
print("Sum = ",arr.sum())

Max =  9
Min =  1
Sum =  22


**10. Generate 5 random numbers between 0 and 1.**

In [24]:
ra = np.random.rand(5)

print(ra)

[0.69412782 0.06885174 0.11586146 0.71873894 0.76233429]


**11. Create a 3D array and access:**

**First block**

**Last element**

In [25]:
a = np.array([
                [[1,2,3],[4,5,6],[7,8,9]],        
                [[10,11,12],[13,14,15],[16,17,18]],
                [[19,20,21],[22,23,24],[25,26,27]]
            ])

print(a.ndim,"Dimension")
print("First Block : ",a[0] )
print("Last Element: ",a[2,2,2])


3 Dimension
First Block :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Last Element:  27


**12. Create a NumPy array and replace all even numbers with 0.**

In [26]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

ar[ar % 2 == 0] = 0

print(ar)

[1 0 3 0 5 0 7 0 9 0]


**13. Find all elements greater than 5:**

In [27]:
arr = np.array([2, 6, 8, 1, 4])

result = arr[arr>5]
print(result)

[6 8]


**14. Create two arrays and perform:**

**Addition**

**Multiplication**

In [28]:
a = np.array([5,9,3,2,6])
b = np.array([2,6,7,3,5])

print("Addition: ",a+b)
print("Multiplication: ",a*b)

Addition:  [ 7 15 10  5 11]
Multiplication:  [10 54 21  6 30]


**Given:
arr = np.array([[1,2,3],[4,5,6]])**

**Find:
Row-wise sum**

**Column-wise sum**

In [29]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.shape
print("Row-wise sum: ",arr.sum(axis=1))
print("Column-wise sum: ", arr.sum(axis=0))

Row-wise sum:  [ 6 15]
Column-wise sum:  [5 7 9]


**Identity Matrix**

In [30]:
identity = np.identity(5)

identity.shape

(5, 5)

**. Random 10 Number** 

In [31]:
random  = np.random.rand(10)

random

array([0.16217416, 0.3837069 , 0.34598129, 0.52263185, 0.96509392,
       0.52626031, 0.34746265, 0.43069853, 0.08478645, 0.25327659])

**Reshape**

In [32]:
a = np.array([1,2,3,4,5,6,7,8,9])

result = a.reshape(3,3)

print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**axis**

**axis 0 -> Row side**

**axis 1 -> column side**

In [55]:
a = np.array([[1,2,3,4], [2,6,8,5]])

print(a.sum(axis = 1))
print(a.sum(axis  = 0))

[10 21]
[ 3  8 11  9]


**Transpose**

In [58]:
a = np.array([[1,2,3,4], [2,6,8,5]])

print(a)

a.T

[[1 2 3 4]
 [2 6 8 5]]


array([[1, 2],
       [2, 6],
       [3, 8],
       [4, 5]])

In [61]:
ar = np.array([    [1,2,3],
                   [4,5,6], 
                   [7,1,0] 
              ])


ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [62]:
ar = np.array([    [1,2,3],
                   [4,5,6], 
                   [7,1,0] 
              ])


ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [70]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
ar2 = np.array([[9,8,7],
                [5,6,2],
                [2,6,3]
               ])

ar+ar2

array([[10, 10, 10],
       [ 9, 11,  8],
       [ 9,  7,  3]])